### ISSUE TITLE
Wrong issue count

### ISSUE THREAD

**Issue by eoli3n** [teoxoy/profile-readme-stats#11]
Thanks for this, nice tool !

Total issue count is wrong.
See https://github.com/eoli3n/eoli3n : it shows 88 commits, but I pushed some thousand commits.

**Comment by teoxoy** [comment]
I think it's because you used a different email address than the one you have on github to commit in some of your repositories. You can notice that by the fact that you can't click on the user and it has no profile picture.

**Comment by eoli3n** [comment]
And I forgot to add ``read:user`` token, fixed this but still.
Yes, I changed my email recently, is there any way to count for multiple emails ?

**Comment by eoli3n** [comment]
> You can notice that by the fact that you can't click on the user and it has no profile picture.

I don't get what you mean here. On which page ?

**Comment by eoli3n** [comment]
Fixed by readding my old email address to github account.

**Comment by eoli3n** [comment]
But still,  it show ~1100, but that's what I have only in dotfiles...

**Comment by teoxoy** [comment]
There still seem to be a bunch of commits pointing to a different email
https://github.com/eoli3n/dotfiles/commits/master?after=b487d28d0020865bd2a40fc6d6126d336e581129+685&branch=master
https://github.com/eoli3n/dotfiles/graphs/contributors

**Comment by eoli3n** [comment]
I was searching in github, thanks for helping !
