### ISSUE TITLE
How to integrate? Need Instructions

### ISSUE THREAD

**Issue by avidraghav** [teoxoy/profile-readme-stats#12]
I'm not able to get whatever documentation is mentioned to integrate it. Kindly provide some instructions such that I can get started with using this repository.

**Comment by avidraghav** [comment]
![image](https://user-images.githubusercontent.com/49483235/120008666-cf8f4600-bff8-11eb-9fc7-7b9e737d56b5.png)
I'm getting this error

**Comment by teoxoy** [comment]
It's not necessary for you to create the `README.md` file beforehand.
You need to pass in your [token](https://github.com/teoxoy/profile-readme-stats#token). You can check github's [docs](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) for more info about secrets.

**Comment by avidraghav** [comment]
Thanks I got this.
