### ISSUE TITLE
Process completed with code 2

### ISSUE THREAD

**Issue by Cyanic76** [teoxoy/profile-readme-stats#14]
Hello,

I'm trying to set up the readme stats but encounter this error: `Process completed with code 2`.

Another error pops up: `/home/runner/work/_temp/37f1f32d-c53e-4ba7-8bf9-46ccfc4a17ee.sh: line 1: conditional binary operator expected`. Is there a way to fix this?

I believe the TEMPLATE.md is correct, though.

**Comment by teoxoy** [comment]
`conditional binary operator expected` is a shell error

Are you sure your workflow file is set up properly?

**Comment by Cyanic76** [comment]
I'm not sure though, [here's what it looks like](https://github.com/Cyanic76/Cyanic76/raw/master/.github/workflows/stats.yml)

**Comment by teoxoy** [comment]
`!==` is not valid in bash. use `!=`

**Comment by Cyanic76** [comment]
Ok, thanks
