### ISSUE TITLE
suddenly not working anymore

### ISSUE THREAD

**Issue by eoli3n** [teoxoy/profile-readme-stats#17]
https://github.com/eoli3n/eoli3n/runs/3970739876?check_suite_focus=true

Any idea ?

**Comment by eoli3n** [comment]
> Hi,
> 
> Any update ? It would be cool to find what is problematic here.
> Is that confirmed that it's a bug ?
> 
> Have a nice day

---

> Hi Jonathan,
> 
> Thanks for the follow-up!
> 
> I have asked the engineering team to help take a look at the cause of this timeout on issue totalCount. I don't have an ETA now but will write back to you if I have any news.
> 
> Regards,
> 
> Oluwaseun
> GitHub Support

**Comment by eoli3n** [comment]
It seems fixed : https://github.com/eoli3n/eoli3n/actions

**Comment by eoli3n** [comment]
The strange part is that my contributed number dropped down : https://github.com/eoli3n/eoli3n/commit/96ca1975a7034f30a19059dd9109f754e0e8332a

**Comment by devmount** [comment]
As far as I can tell it looks like it's fixed, but it isn't. It sometimes works and sometimes not: https://github.com/devmount/devmount/actions

My raw guess is, it only works if you created an issue in the meantime...

**Comment by eoli3n** [comment]
> if you created an issue in the meantime

I don't get what you mean, created an issue where ?

**Comment by eoli3n** [comment]
Just reopened the ticket

> Is this fixed ? I just found that ticket closed but can't find when it was closed.
> 
> I seems working better since yesterday for me:
> https://github.com/eoli3n/eoli3n/actions
> 
> But for another user, it's more random:
> https://github.com/devmount/devmount/actions
> 
> Any update ?

**Comment by devmount** [comment]
Sorry 😇 I meant that if you have the issues counter in your template and one of your contributions since the last run of the action was the creation of a GitHub issue on any public repository, the action succeeds. If not, it fails. But as I already said: that's just a wild guess since didn't take the time to test this...

**Comment by devmount** [comment]
> The strange part is that my contributed number dropped down : [eoli3n/eoli3n@96ca197](https://github.com/eoli3n/eoli3n/commit/96ca1975a7034f30a19059dd9109f754e0e8332a)

Yes, I observed that too some time ago: https://github.com/devmount/devmount/commit/0f36a6357b6c416ff7b8f7f8fdb5684a3a870e20

**Comment by eoli3n** [comment]
> if you have the issues counter in your template and one of your contributions since the last run of the action was the creation of a GitHub issue on any public repository, the action succeeds

In my case, no issue created before it starts working again.

**Comment by devmount** [comment]
Okay, then it was a coincidence in my case. But still: It works only sometimes.

**Comment by eoli3n** [comment]
@teoxoy as said in https://github.com/teoxoy/profile-readme-stats/issues/17#issuecomment-952651766, support asks to query in two parts. Would you like to implement the workaround please ?

> Can you implement a workaround by running a separate query for OPEN and CLOSE issue counts separately?
```
    issues(states: [CLOSED]) {
      totalCount
    }
```
```
    issues(states: [OPEN]) {
      totalCount
    }
```

**Comment by eoli3n** [comment]
@teoxoy the support guy gave me that exemple : https://github.com/anuraghazra/github-readme-stats/pull/1409/files

**Comment by devmount** [comment]
Yes I can do that, give me some time.

**Comment by devmount** [comment]
I created the fix in my fork and [it seems to work](https://github.com/devmount/devmount/actions/runs/1506560058). I created PR #19 for this, merge it if you like.

**Comment by teoxoy** [comment]
@eoli3n @devmount are you guys still running into this issue?

**Comment by devmount** [comment]
No, it's working fine for me for more than a year now 🤷🏻

**Comment by eoli3n** [comment]
No problem for me too, since a long time.

**Comment by teoxoy** [comment]
Great!
