### ISSUE TITLE
Not adding the counts in private repositories.

### ISSUE THREAD

**Issue by thisisamank** [teoxoy/profile-readme-stats#20]
I have around 900 commits in total including commits in private repos but it is counting 700 commits...seems like there is some issue with it.

**Comment by teoxoy** [comment]
How did you count those 900 commits? I checked your profile and github lists around 900 contributions - github defines contributions as:

- Committing to a repository's default branch or gh-pages branch
- Opening an issue
- Opening a discussion
- Answering a discussion
- Proposing a pull request
- Submitting a pull request review

[reference](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/viewing-contributions-on-your-profile#what-counts-as-a-contribution)

**Comment by thisisamank** [comment]
Oh, I got it. Thanks a lot for clearing it out.
