### ISSUE TITLE
Auto readme isn't working with Node16

### ISSUE THREAD

**Issue by M8-Babbage** [teoxoy/profile-readme-stats#21]
Hi, recently github updated its configuration for actions from nodejs 12 to 16, but, the project now isn't working

Here a picture with the prompt from actions.
![image](https://user-images.githubusercontent.com/119270803/215868196-b78b4667-7481-4163-b106-03776518f76c.png)

finally when the actions are running i get this error
![image](https://user-images.githubusercontent.com/119270803/215868982-30259f37-a29a-45d7-8b9f-756436f6814f.png)

**Comment by teoxoy** [comment]
Thanks for reminding me! I released v2.

**Comment by teoxoy** [comment]
It won't commit if nothing changed.
You went to 0 commits here, previous to the update - not sure why. Check/regenerate the token.
https://github.com/M8-Babbage/M8-Babbage/commit/0fc9f409787ef2efa4653b6fa4cbd6e23d755d1a

**Comment by M8-Babbage** [comment]
Ok, I found the problem, my profile was private, therefore the confirmations are not available, thanks for your help!
