### ISSUE TITLE
Commits and Pull requests number decreased

### ISSUE THREAD

**Issue by avidraghav** [teoxoy/profile-readme-stats#22]
My Commits and Pull Requests were decreased by the github action, how can I fix this?
<img width="1064" alt="Screenshot 2023-03-01 at 7 18 45 PM" src="https://user-images.githubusercontent.com/49483235/222157769-e6b9c1af-4c3e-425e-9f6f-f7aa142fc51a.png">

**Comment by teoxoy** [comment]
Did you make one of your repos private?

**Comment by avidraghav** [comment]
No, I didn't. I clearly remember that I didn't make any private in which I made around 200 commits.

**Comment by avidraghav** [comment]
Any Solution to the above problem? I can provide additional data you want. I'm afraid that I'll have to stop using the action if this issue isn't resolved.

**Comment by teoxoy** [comment]
It's difficult to know what happened. You could try running the GraphQL queries this action runs manually and checking their results. This might be an issue with the results github's GraphQL API returns.

**Comment by avidraghav** [comment]
I see, can u send the sample query with other instructions? I'm not well versed with GraphQL

**Comment by teoxoy** [comment]
Try to run the query below here: https://docs.github.com/en/graphql/overview/explorer

```gql
query { 
  viewer { 
    repositoriesContributedTo(first: 10) {
      nodes {
        nameWithOwner
      }
      totalCount
    }
  }
}
```

and see if there are any noteworthy public repos that you contributed to missing.

I suspect one of them where you contributed ~200 commits is missing (either became private or got deleted).

**Comment by avidraghav** [comment]
I ran the query and none of the repositories it returned got deleted.

**Comment by teoxoy** [comment]
I mean, there must be one that's missing.
Count went from 4 to 3 (it's 5 now because you recently contributed to this repo and one more)

**Comment by avidraghav** [comment]
I try running this
https://github-readme-stats.vercel.app/api?username=avidraghav&count_private=true&include_all_commits=true
It's showing the perfect commit count. If I had made a repo private then that would have reflected here too.

**Comment by teoxoy** [comment]
![image](https://user-images.githubusercontent.com/28601907/223101981-99a7071c-f0de-4a6c-a1e6-5fadc716972d.png)

This is what I see there.

![image](https://user-images.githubusercontent.com/28601907/223102364-f7987573-ddf3-4e2f-8dbd-dff29222249c.png)

And this is on your profile generated by this action.

The only stat that is way off is the nr of total commits.

![image](https://user-images.githubusercontent.com/49483235/222157769-e6b9c1af-4c3e-425e-9f6f-f7aa142fc51a.png)

In this image (first one you posted) the nr of PRs also went down and is the same as the one reported by https://github.com/anuraghazra/github-readme-stats

**Comment by teoxoy** [comment]
I don't think there is any way to do that unless you keep a record/history of all the queries the GraphQL API returned.

**Comment by avidraghav** [comment]
It's strange I guess, If I'm using this query than I'm getting the commits from the repository which I lost access to. The PR count has decreased but the commit count is same. The query params I have added are just for formatting sakes.
https://github-readme-stats.vercel.app/api?username=avidraghav&count_private=true&include_all_commits=true&show_icons=true&show_icons=true&title_color=ffffff&icon_color=bb2acf&text_color=daf7dc&bg_color=151515
