### ISSUE TITLE
ignore bot commits

### ISSUE THREAD

**Issue by eoli3n** [teoxoy/profile-readme-stats#24]
I just tried to fix my count, by excluding bot commit count as https://github.com/eoli3n/eoli3n/commit/50de2332337e4b45cdb1025b5053335e5d68fea3

And
```
$ git config user.name "Bot"
$ git config user.email "bot@github.com"
$ git rebase -r --root --exec "git commit --amend --no-edit --reset-author"
$ git push --force
```

https://github.com/eoli3n/eoli3n/commits/main

Now user/email for those commits dismatches my account email, but commits still appear in count and contribution grid.
Any idea ?

**Comment by eoli3n** [comment]
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-less-than-24-hours-ago

**Comment by teoxoy** [comment]
I'd just use (they are also in the readme):

```
git config user.name github-actions[bot]
git config user.email 41898282+github-actions[bot]@users.noreply.github.com
```

I don't remember where exactly I got those from but they've been working well for me.

**Comment by teoxoy** [comment]
Using a bot user should be the proper way to commit these updates, closing.
