### ISSUE TITLE
Distinguish between private and public repositories

### ISSUE THREAD

**Issue by DSiekmeier** [teoxoy/profile-readme-stats#26]
Thanks for this nice project!

I wonder if there is a way to implement the possibility to distinguish between private and public repositories. For example I would like to see the top programming languages for public repos only.

Kind Regards, Dennis

**Comment by teoxoy** [comment]
I think this is possible already, if the access token doesn't include private repositories, private repository data won't be available.

The readme hints at this but is not very explicit.

**Comment by DSiekmeier** [comment]
This does not exactly fulfills my requirement, because one cannot show a statistic like

> There are x public and y private repositories.

But thanks for your answer. Kind Regards.
