### ISSUE TITLE
Feature request: BIO

### ISSUE THREAD

**Issue by Milo123459** [teoxoy/profile-readme-stats#4]
Get the bio on your github account, ie, {{ BIO }} would return being unproductive for me.

**Comment by teoxoy** [comment]
If the piece of text is already in your github bio, why put it on the readme?

**Comment by Milo123459** [comment]
Why not? 😅

**Comment by teoxoy** [comment]
I mean, it's just duplicated information. People that visit your profile, will most likely look at your bio first and then check the readme for more info. What's the point of having the same bio in the readme?

**Comment by Milo123459** [comment]
Suppose you have a point, how about a {{ SPONSORS }} like the languages system and a {{ STARRED }} to display how many repositories you've stared

**Comment by teoxoy** [comment]
Sponsors and nr of starred repos is also already part of the info shown on the left side😅

**Comment by Milo123459** [comment]
😅

How about {{ WAKATIME_TODAY }} which displays how many minutes & hours you have coded on this specific day via wakatime?

**Comment by teoxoy** [comment]
Sorry, Wakatime is out of scope. There are also other actions that integrate with wakatime.

**Comment by Milo123459** [comment]
Oh...
