### ISSUE TITLE
Warning: Unexpected input(s) 'includeForks', valid inputs are ['token', 'template', 'readme']

### ISSUE THREAD

**Issue by PuneetGopinath** [teoxoy/profile-readme-stats#7]
includeForks is not working
I think it's because you did not publish a new release after adding includeForks.
Can you publish 1.2?
Or will I use your master branch instead?

**Comment by teoxoy** [comment]
There was a v1.1 release but was not published on the marketplace (I think I forgot to do it).
I just pushed v1.1 on the marketplace.

**Comment by PuneetGopinath** [comment]
Thanks
