### ISSUE TITLE
Feature Request: Code Reviews

### ISSUE THREAD

**Issue by aitikgupta** [teoxoy/profile-readme-stats#9]
Hi, thanks for the amazing utility. 💯 
I was wondering if it's feasible enough to provide support for Code Reviews?

There are 4 pillars to GitHub's activity overview - Commits [supported], Pull Requests [supported], Issues [supported], and lastly Code review [unsupported]
![image](https://user-images.githubusercontent.com/43996118/118588670-818a6f00-b7bc-11eb-9d26-ebe6fd4f7731.png)

I don't think (?) there's a straightforward GraphQL query that GitHub provides (could be wrong).

Is there any workaround (if it's even feasible)?

**Comment by teoxoy** [comment]
Thanks!

I think you can get that info by adding `totalPullRequestReviewContributions` here:
https://github.com/teoxoy/profile-readme-stats/blob/57da79551137662a3025d908c0e8015d6298f4f0/src/main.ts#L196

I don't have the bandwidth to add this now though. PRs are welcome
